Fix/action_generate-api-client (#581)
* Fixes error in action publish package: https://github.com/metanull/inventory-app/actions/runs/21187538037/job/60946034720

```
Your lock file does not contain a compatible set of packages. Please run composer update.
Error: Process completed with exit code 2.
```

The issue seems to be at line 30 in the action.yml:30, the workflow; it is using composer install with the --no-scripts flag: The problem is that --no-scripts prevents composer from running the post-autoload-dump and other scripts defined in your composer.json. When you run composer update locally, these scripts execute, potentially updating the lock file with additional metadata or dependencies. However, in the CI workflow, since these scripts don't run, Composer detects a mismatch between what the lock file expects and what the install produces.

* 6.5.4

---------

Co-authored-by: Pascal HAVELANGE <havelangep@hotmail.com>